image:
  - Visual Studio 2019
platform:
  - x64
configuration: Release
cache: 
  - c:\tools\vcpkg\installed\

environment:
  QT_DIR: C:\Qt\latest\msvc2019_64
  BOOST_DIR: C:\Libraries\boost_1_73_0
  VCPKG_DIR: C:\tools\vcpkg

init:
  - set PATH=%QT_DIR%\bin;%PATH%
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%

install:
  - vcpkg install --triplet x64-windows zlib openssl websocketpp brotli boost
  - vcpkg integrate install

before_build:
  - mkdir build
  - cd build

build_script:
  - cmake .. -DCMAKE_PREFIX_PATH=%QT_DIR%;%BOOST_DIR% -DCMAKE_TOOLCHAIN_FILE=%VCPKG_DIR%\scripts\buildsystems\vcpkg.cmake
  - devenv Backing.sln /deploy Release
  - cpack
  - type build/_CPack_Packages/win64/NSIS/NSISOutput.log
  - copy Backing-*.exe %APPVEYOR_BUILD_FOLDER%\backing_win_x64.exe

artifacts:
  - path: backing_win_x64.exe
    name: backing

deploy:
  description: 'Backing'
  provider: GitHub
  auth_token:
    secure: NDr/N5HpkiZPeC2OHiDDA7Xx4QGb4WAJRr81qmZdIyX0BjLx24Cq1aIeANT5w55U
  artifact: backing_win_x64.exe
  draft: false
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true