image:
  - Visual Studio 2019

before_build:
  - mkdir build
  - cd build

build_script:
  - cmake .. -DCMAKE_PREFIX_PATH=C:\Libraries\boost_1_73_0 -DCMAKE_PREFIX_PATH=C:\OpenSSL-Win64\bin
  - nmake backing