image:
  - Visual Studio 2019
platform:
  - x64

init:
  - set PATH=C:\Libraries\boost_1_73_0;C:\OpenSSL-Win64\bin;C:\Qt\5.14.2;%PATH%
  - set makefiles="NMake Makefiles"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" %PLATFORM%

install:
  - vcpkg install --triplet x64-windows zlib openssl boost-system boost-date-time boost-regex boost-interprocess websocketpp brotli

before_build:
  - mkdir build
  - cd build

build_script:
  - cmake .. -DCMAKE_PREFIX_PATH=C:/Tools/vcpkg/packages/zlib_x64-windows/share/zlib
  - nmake backing